name = "radiance"
version = "0.0.1"
description = "Wayland implementation for gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "morr0ne", repo = "radiance" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
